# Generated by Django 2.1.7 on 2019-04-06 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created',)},
        ),
    ]
