# Generated by Django 2.1.7 on 2019-04-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_auto_20190408_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='total_likes',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
