# Generated by Django 2.1.7 on 2019-05-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_remove_image_total_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='about',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
